/* Localised copy for the ConverterHubPage (/{lang}/convert), 12 languages.
   Kept self-contained (like ContactModal) — falls back to English. Format
   labels (Word, Excel, JPG…) and reviewer names stay as-is across languages. */
export interface HubStrings {
  eyebrow: string; h1: string; sub: string;
  drag: string; selectBtn: string; anyFormat: string;
  uploaded: string; change: string;
  whichFormat: string; unsupported: string;
  convertTo: string; // "Convert to {f}"
  converting: string; ready: string; download: string; preparing: string; convertAnother: string;
  allConversions: string;
  trustPrivate: string; trustDevice: string; trustNoInstall: string;
  howKicker: string; howTitle: string;
  step1Title: string; step1Desc: string; step2Title: string; step2Desc: string; step3Title: string; step3Desc: string;
  reviewsKicker: string; reviewsTitle: string; review1: string; review2: string; review3: string;
  faqKicker: string; faq1Q: string; faq1A: string; faq2Q: string; faq2A: string; faq3Q: string; faq3A: string; faq4Q: string; faq4A: string;
  toastConverting: string; toastDone: string; toastError: string;
}

export const HUB_STRINGS: Record<string, HubStrings> = {
  es: {
    eyebrow: "Conversor de archivos", h1: "Convierte cualquier archivo", sub: "Sube tu archivo y te decimos a qué puedes convertirlo. O elige abajo.",
    drag: "Arrastra tu archivo aquí", selectBtn: "Seleccionar archivo", anyFormat: "Cualquier formato · hasta 100 MB",
    uploaded: "Archivo subido", change: "Cambiar",
    whichFormat: "¿A qué formato lo convertimos?", unsupported: "Todavía no podemos convertir este tipo de archivo.",
    convertTo: "Convertir a {f}",
    converting: "Convirtiendo tu archivo…", ready: "¡Tu archivo está listo!", download: "Descargar", preparing: "Preparando…", convertAnother: "Convertir a otro formato",
    allConversions: "Todas las conversiones",
    trustPrivate: "Privado y seguro", trustDevice: "Cualquier dispositivo", trustNoInstall: "Sin instalación",
    howKicker: "Cómo funciona", howTitle: "Convierte en 3 pasos",
    step1Title: "1. Sube tu archivo", step1Desc: "Arrastra o selecciona cualquier archivo. Detectamos el tipo automáticamente.",
    step2Title: "2. Elige el formato", step2Desc: "Te mostramos a qué puedes convertirlo. Pulsa el que quieras.",
    step3Title: "3. Descarga al instante", step3Desc: "Convertimos tu archivo y lo descargas en segundos.",
    reviewsKicker: "Lo que dicen", reviewsTitle: "Miles de archivos convertidos",
    review1: "Convertí un PDF a Word en segundos y respetó todo el formato. Perfecto.", review2: "Por fin pude pasar las fotos HEIC de mi iPhone a JPG. Rapidísimo.", review3: "Sin instalar nada: subo el archivo y descargo. Muy fácil.",
    faqKicker: "Preguntas frecuentes",
    faq1Q: "¿Es seguro subir mis archivos?", faq1A: "Sí. Los archivos se procesan de forma segura y no se comparten con terceros.",
    faq2Q: "¿Qué formatos puedo convertir?", faq2A: "PDF ↔ Word, Excel, PowerPoint, JPG y PNG, además de HEIC→JPG, WEBP→JPG y HTML→PDF.",
    faq3Q: "¿Necesito instalar algo?", faq3A: "No. Todo funciona en el navegador, en cualquier dispositivo.",
    faq4Q: "¿Cuánto cuesta?", faq4A: "0,50 € por conversión.",
    toastConverting: "Convirtiendo…", toastDone: "¡Listo! Descarga iniciada.", toastError: "No se pudo convertir el archivo.",
  },
  en: {
    eyebrow: "File converter", h1: "Convert any file", sub: "Upload your file and we'll tell you what you can convert it to. Or pick below.",
    drag: "Drag your file here", selectBtn: "Select file", anyFormat: "Any format · up to 100 MB",
    uploaded: "File uploaded", change: "Change",
    whichFormat: "What format should we convert to?", unsupported: "We can't convert this file type yet.",
    convertTo: "Convert to {f}",
    converting: "Converting your file…", ready: "Your file is ready!", download: "Download", preparing: "Preparing…", convertAnother: "Convert to another format",
    allConversions: "All conversions",
    trustPrivate: "Private & secure", trustDevice: "Any device", trustNoInstall: "No installation",
    howKicker: "How it works", howTitle: "Convert in 3 steps",
    step1Title: "1. Upload your file", step1Desc: "Drag or select any file. We detect the type automatically.",
    step2Title: "2. Choose the format", step2Desc: "We show you what you can convert it to. Click the one you want.",
    step3Title: "3. Download instantly", step3Desc: "We convert your file and you download it in seconds.",
    reviewsKicker: "What people say", reviewsTitle: "Thousands of files converted",
    review1: "I converted a PDF to Word in seconds and it kept all the formatting. Perfect.", review2: "I could finally turn my iPhone HEIC photos into JPG. Super fast.", review3: "No installing anything: I upload the file and download. Very easy.",
    faqKicker: "Frequently asked questions",
    faq1Q: "Is it safe to upload my files?", faq1A: "Yes. Files are processed securely and not shared with third parties.",
    faq2Q: "What formats can I convert?", faq2A: "PDF ↔ Word, Excel, PowerPoint, JPG and PNG, plus HEIC→JPG, WEBP→JPG and HTML→PDF.",
    faq3Q: "Do I need to install anything?", faq3A: "No. Everything works in the browser, on any device.",
    faq4Q: "How much does it cost?", faq4A: "0.50 € per conversion.",
    toastConverting: "Converting…", toastDone: "Done! Download started.", toastError: "Couldn't convert the file.",
  },
  fr: {
    eyebrow: "Convertisseur de fichiers", h1: "Convertissez n'importe quel fichier", sub: "Envoyez votre fichier et nous vous dirons vers quoi le convertir. Ou choisissez ci-dessous.",
    drag: "Glissez votre fichier ici", selectBtn: "Sélectionner un fichier", anyFormat: "Tout format · jusqu'à 100 Mo",
    uploaded: "Fichier envoyé", change: "Changer",
    whichFormat: "Vers quel format le convertir ?", unsupported: "Nous ne pouvons pas encore convertir ce type de fichier.",
    convertTo: "Convertir en {f}",
    converting: "Conversion de votre fichier…", ready: "Votre fichier est prêt !", download: "Télécharger", preparing: "Préparation…", convertAnother: "Convertir vers un autre format",
    allConversions: "Toutes les conversions",
    trustPrivate: "Privé et sécurisé", trustDevice: "Tout appareil", trustNoInstall: "Sans installation",
    howKicker: "Comment ça marche", howTitle: "Convertissez en 3 étapes",
    step1Title: "1. Envoyez votre fichier", step1Desc: "Glissez ou sélectionnez n'importe quel fichier. Nous détectons le type automatiquement.",
    step2Title: "2. Choisissez le format", step2Desc: "Nous vous montrons vers quoi le convertir. Cliquez sur celui que vous voulez.",
    step3Title: "3. Téléchargez instantanément", step3Desc: "Nous convertissons votre fichier et vous le téléchargez en quelques secondes.",
    reviewsKicker: "Ce qu'ils disent", reviewsTitle: "Des milliers de fichiers convertis",
    review1: "J'ai converti un PDF en Word en quelques secondes et la mise en page a été respectée. Parfait.", review2: "J'ai enfin pu convertir les photos HEIC de mon iPhone en JPG. Très rapide.", review3: "Sans rien installer : j'envoie le fichier et je télécharge. Très facile.",
    faqKicker: "Questions fréquentes",
    faq1Q: "Est-ce sûr d'envoyer mes fichiers ?", faq1A: "Oui. Les fichiers sont traités en toute sécurité et ne sont pas partagés avec des tiers.",
    faq2Q: "Quels formats puis-je convertir ?", faq2A: "PDF ↔ Word, Excel, PowerPoint, JPG et PNG, ainsi que HEIC→JPG, WEBP→JPG et HTML→PDF.",
    faq3Q: "Dois-je installer quelque chose ?", faq3A: "Non. Tout fonctionne dans le navigateur, sur n'importe quel appareil.",
    faq4Q: "Combien ça coûte ?", faq4A: "0,50 € par conversion.",
    toastConverting: "Conversion…", toastDone: "Terminé ! Téléchargement lancé.", toastError: "Impossible de convertir le fichier.",
  },
  de: {
    eyebrow: "Datei-Konverter", h1: "Konvertiere jede Datei", sub: "Lade deine Datei hoch und wir sagen dir, wohin du sie konvertieren kannst. Oder wähle unten.",
    drag: "Ziehe deine Datei hierher", selectBtn: "Datei auswählen", anyFormat: "Jedes Format · bis zu 100 MB",
    uploaded: "Datei hochgeladen", change: "Ändern",
    whichFormat: "In welches Format konvertieren?", unsupported: "Diesen Dateityp können wir noch nicht konvertieren.",
    convertTo: "In {f} konvertieren",
    converting: "Deine Datei wird konvertiert…", ready: "Deine Datei ist fertig!", download: "Herunterladen", preparing: "Wird vorbereitet…", convertAnother: "In ein anderes Format konvertieren",
    allConversions: "Alle Konvertierungen",
    trustPrivate: "Privat und sicher", trustDevice: "Jedes Gerät", trustNoInstall: "Keine Installation",
    howKicker: "So funktioniert's", howTitle: "In 3 Schritten konvertieren",
    step1Title: "1. Datei hochladen", step1Desc: "Ziehe oder wähle eine beliebige Datei. Wir erkennen den Typ automatisch.",
    step2Title: "2. Format wählen", step2Desc: "Wir zeigen dir, wohin du sie konvertieren kannst. Klicke auf das gewünschte.",
    step3Title: "3. Sofort herunterladen", step3Desc: "Wir konvertieren deine Datei und du lädst sie in Sekunden herunter.",
    reviewsKicker: "Das sagen andere", reviewsTitle: "Tausende Dateien konvertiert",
    review1: "Ich habe ein PDF in Sekunden in Word umgewandelt und die Formatierung blieb erhalten. Perfekt.", review2: "Endlich konnte ich die HEIC-Fotos meines iPhones in JPG umwandeln. Superschnell.", review3: "Ohne Installation: Datei hochladen und herunterladen. Sehr einfach.",
    faqKicker: "Häufige Fragen",
    faq1Q: "Ist das Hochladen meiner Dateien sicher?", faq1A: "Ja. Die Dateien werden sicher verarbeitet und nicht an Dritte weitergegeben.",
    faq2Q: "Welche Formate kann ich konvertieren?", faq2A: "PDF ↔ Word, Excel, PowerPoint, JPG und PNG sowie HEIC→JPG, WEBP→JPG und HTML→PDF.",
    faq3Q: "Muss ich etwas installieren?", faq3A: "Nein. Alles läuft im Browser, auf jedem Gerät.",
    faq4Q: "Wie viel kostet es?", faq4A: "0,50 € pro Konvertierung.",
    toastConverting: "Konvertierung…", toastDone: "Fertig! Download gestartet.", toastError: "Datei konnte nicht konvertiert werden.",
  },
  pt: {
    eyebrow: "Conversor de ficheiros", h1: "Converte qualquer ficheiro", sub: "Carrega o teu ficheiro e dizemos-te para que o podes converter. Ou escolhe abaixo.",
    drag: "Arrasta o teu ficheiro aqui", selectBtn: "Selecionar ficheiro", anyFormat: "Qualquer formato · até 100 MB",
    uploaded: "Ficheiro carregado", change: "Alterar",
    whichFormat: "Para que formato convertemos?", unsupported: "Ainda não conseguimos converter este tipo de ficheiro.",
    convertTo: "Converter para {f}",
    converting: "A converter o teu ficheiro…", ready: "O teu ficheiro está pronto!", download: "Descarregar", preparing: "A preparar…", convertAnother: "Converter para outro formato",
    allConversions: "Todas as conversões",
    trustPrivate: "Privado e seguro", trustDevice: "Qualquer dispositivo", trustNoInstall: "Sem instalação",
    howKicker: "Como funciona", howTitle: "Converte em 3 passos",
    step1Title: "1. Carrega o teu ficheiro", step1Desc: "Arrasta ou seleciona qualquer ficheiro. Detetamos o tipo automaticamente.",
    step2Title: "2. Escolhe o formato", step2Desc: "Mostramos-te para que o podes converter. Clica no que quiseres.",
    step3Title: "3. Descarrega ao instante", step3Desc: "Convertemos o teu ficheiro e descarregas em segundos.",
    reviewsKicker: "O que dizem", reviewsTitle: "Milhares de ficheiros convertidos",
    review1: "Converti um PDF para Word em segundos e manteve toda a formatação. Perfeito.", review2: "Finalmente consegui passar as fotos HEIC do meu iPhone para JPG. Rapidíssimo.", review3: "Sem instalar nada: carrego o ficheiro e descarrego. Muito fácil.",
    faqKicker: "Perguntas frequentes",
    faq1Q: "É seguro carregar os meus ficheiros?", faq1A: "Sim. Os ficheiros são processados de forma segura e não são partilhados com terceiros.",
    faq2Q: "Que formatos posso converter?", faq2A: "PDF ↔ Word, Excel, PowerPoint, JPG e PNG, além de HEIC→JPG, WEBP→JPG e HTML→PDF.",
    faq3Q: "Preciso de instalar algo?", faq3A: "Não. Tudo funciona no navegador, em qualquer dispositivo.",
    faq4Q: "Quanto custa?", faq4A: "0,50 € por conversão.",
    toastConverting: "A converter…", toastDone: "Pronto! Descarga iniciada.", toastError: "Não foi possível converter o ficheiro.",
  },
  it: {
    eyebrow: "Convertitore di file", h1: "Converti qualsiasi file", sub: "Carica il tuo file e ti diremo in cosa puoi convertirlo. Oppure scegli qui sotto.",
    drag: "Trascina qui il tuo file", selectBtn: "Seleziona file", anyFormat: "Qualsiasi formato · fino a 100 MB",
    uploaded: "File caricato", change: "Cambia",
    whichFormat: "In quale formato lo convertiamo?", unsupported: "Non possiamo ancora convertire questo tipo di file.",
    convertTo: "Converti in {f}",
    converting: "Conversione del file in corso…", ready: "Il tuo file è pronto!", download: "Scarica", preparing: "Preparazione…", convertAnother: "Converti in un altro formato",
    allConversions: "Tutte le conversioni",
    trustPrivate: "Privato e sicuro", trustDevice: "Qualsiasi dispositivo", trustNoInstall: "Nessuna installazione",
    howKicker: "Come funziona", howTitle: "Converti in 3 passaggi",
    step1Title: "1. Carica il tuo file", step1Desc: "Trascina o seleziona qualsiasi file. Rileviamo il tipo automaticamente.",
    step2Title: "2. Scegli il formato", step2Desc: "Ti mostriamo in cosa puoi convertirlo. Clicca quello che vuoi.",
    step3Title: "3. Scarica subito", step3Desc: "Convertiamo il tuo file e lo scarichi in pochi secondi.",
    reviewsKicker: "Cosa dicono", reviewsTitle: "Migliaia di file convertiti",
    review1: "Ho convertito un PDF in Word in pochi secondi e ha mantenuto tutta la formattazione. Perfetto.", review2: "Finalmente ho potuto convertire le foto HEIC del mio iPhone in JPG. Velocissimo.", review3: "Senza installare nulla: carico il file e scarico. Molto facile.",
    faqKicker: "Domande frequenti",
    faq1Q: "È sicuro caricare i miei file?", faq1A: "Sì. I file vengono elaborati in modo sicuro e non condivisi con terzi.",
    faq2Q: "Quali formati posso convertire?", faq2A: "PDF ↔ Word, Excel, PowerPoint, JPG e PNG, oltre a HEIC→JPG, WEBP→JPG e HTML→PDF.",
    faq3Q: "Devo installare qualcosa?", faq3A: "No. Tutto funziona nel browser, su qualsiasi dispositivo.",
    faq4Q: "Quanto costa?", faq4A: "0,50 € per conversione.",
    toastConverting: "Conversione…", toastDone: "Fatto! Download avviato.", toastError: "Impossibile convertire il file.",
  },
  nl: {
    eyebrow: "Bestandsconverter", h1: "Converteer elk bestand", sub: "Upload je bestand en we vertellen je waarnaar je het kunt converteren. Of kies hieronder.",
    drag: "Sleep je bestand hierheen", selectBtn: "Bestand kiezen", anyFormat: "Elk formaat · tot 100 MB",
    uploaded: "Bestand geüpload", change: "Wijzigen",
    whichFormat: "Naar welk formaat converteren?", unsupported: "Dit bestandstype kunnen we nog niet converteren.",
    convertTo: "Converteren naar {f}",
    converting: "Je bestand wordt geconverteerd…", ready: "Je bestand is klaar!", download: "Downloaden", preparing: "Voorbereiden…", convertAnother: "Naar een ander formaat converteren",
    allConversions: "Alle conversies",
    trustPrivate: "Privé en veilig", trustDevice: "Elk apparaat", trustNoInstall: "Geen installatie",
    howKicker: "Hoe het werkt", howTitle: "Converteer in 3 stappen",
    step1Title: "1. Upload je bestand", step1Desc: "Sleep of selecteer een bestand. We detecteren het type automatisch.",
    step2Title: "2. Kies het formaat", step2Desc: "We laten zien waarnaar je het kunt converteren. Klik op wat je wilt.",
    step3Title: "3. Direct downloaden", step3Desc: "We converteren je bestand en je downloadt het in seconden.",
    reviewsKicker: "Wat men zegt", reviewsTitle: "Duizenden bestanden geconverteerd",
    review1: "Ik heb een PDF in seconden naar Word omgezet en alle opmaak bleef behouden. Perfect.", review2: "Ik kon eindelijk de HEIC-foto's van mijn iPhone naar JPG omzetten. Supersnel.", review3: "Zonder iets te installeren: bestand uploaden en downloaden. Heel eenvoudig.",
    faqKicker: "Veelgestelde vragen",
    faq1Q: "Is het veilig om mijn bestanden te uploaden?", faq1A: "Ja. Bestanden worden veilig verwerkt en niet met derden gedeeld.",
    faq2Q: "Welke formaten kan ik converteren?", faq2A: "PDF ↔ Word, Excel, PowerPoint, JPG en PNG, plus HEIC→JPG, WEBP→JPG en HTML→PDF.",
    faq3Q: "Moet ik iets installeren?", faq3A: "Nee. Alles werkt in de browser, op elk apparaat.",
    faq4Q: "Hoeveel kost het?", faq4A: "0,50 € per conversie.",
    toastConverting: "Converteren…", toastDone: "Klaar! Download gestart.", toastError: "Kon het bestand niet converteren.",
  },
  pl: {
    eyebrow: "Konwerter plików", h1: "Konwertuj dowolny plik", sub: "Prześlij swój plik, a powiemy Ci, na co możesz go przekonwertować. Lub wybierz poniżej.",
    drag: "Przeciągnij tutaj swój plik", selectBtn: "Wybierz plik", anyFormat: "Dowolny format · do 100 MB",
    uploaded: "Plik przesłany", change: "Zmień",
    whichFormat: "Na jaki format przekonwertować?", unsupported: "Nie możemy jeszcze przekonwertować tego typu pliku.",
    convertTo: "Konwertuj na {f}",
    converting: "Konwertowanie pliku…", ready: "Twój plik jest gotowy!", download: "Pobierz", preparing: "Przygotowywanie…", convertAnother: "Konwertuj na inny format",
    allConversions: "Wszystkie konwersje",
    trustPrivate: "Prywatne i bezpieczne", trustDevice: "Dowolne urządzenie", trustNoInstall: "Bez instalacji",
    howKicker: "Jak to działa", howTitle: "Konwertuj w 3 krokach",
    step1Title: "1. Prześlij plik", step1Desc: "Przeciągnij lub wybierz dowolny plik. Automatycznie wykryjemy jego typ.",
    step2Title: "2. Wybierz format", step2Desc: "Pokażemy Ci, na co możesz go przekonwertować. Kliknij wybrany.",
    step3Title: "3. Pobierz natychmiast", step3Desc: "Konwertujemy Twój plik, a Ty pobierasz go w kilka sekund.",
    reviewsKicker: "Co mówią", reviewsTitle: "Tysiące przekonwertowanych plików",
    review1: "Przekonwertowałem PDF na Word w kilka sekund i zachował całe formatowanie. Idealnie.", review2: "W końcu mogłem zamienić zdjęcia HEIC z iPhone'a na JPG. Superszybko.", review3: "Bez instalowania czegokolwiek: przesyłam plik i pobieram. Bardzo łatwe.",
    faqKicker: "Najczęstsze pytania",
    faq1Q: "Czy przesyłanie plików jest bezpieczne?", faq1A: "Tak. Pliki są przetwarzane bezpiecznie i nie są udostępniane osobom trzecim.",
    faq2Q: "Jakie formaty mogę konwertować?", faq2A: "PDF ↔ Word, Excel, PowerPoint, JPG i PNG, a także HEIC→JPG, WEBP→JPG i HTML→PDF.",
    faq3Q: "Czy muszę coś instalować?", faq3A: "Nie. Wszystko działa w przeglądarce, na dowolnym urządzeniu.",
    faq4Q: "Ile to kosztuje?", faq4A: "0,50 € za konwersję.",
    toastConverting: "Konwertowanie…", toastDone: "Gotowe! Pobieranie rozpoczęte.", toastError: "Nie udało się przekonwertować pliku.",
  },
  ru: {
    eyebrow: "Конвертер файлов", h1: "Конвертируйте любой файл", sub: "Загрузите файл, и мы подскажем, во что его можно конвертировать. Или выберите ниже.",
    drag: "Перетащите файл сюда", selectBtn: "Выбрать файл", anyFormat: "Любой формат · до 100 МБ",
    uploaded: "Файл загружен", change: "Изменить",
    whichFormat: "В какой формат конвертировать?", unsupported: "Мы пока не можем конвертировать этот тип файла.",
    convertTo: "Конвертировать в {f}",
    converting: "Конвертируем ваш файл…", ready: "Ваш файл готов!", download: "Скачать", preparing: "Подготовка…", convertAnother: "Конвертировать в другой формат",
    allConversions: "Все конвертации",
    trustPrivate: "Конфиденциально и безопасно", trustDevice: "Любое устройство", trustNoInstall: "Без установки",
    howKicker: "Как это работает", howTitle: "Конвертируйте за 3 шага",
    step1Title: "1. Загрузите файл", step1Desc: "Перетащите или выберите любой файл. Мы определим тип автоматически.",
    step2Title: "2. Выберите формат", step2Desc: "Мы покажем, во что можно конвертировать. Нажмите на нужный.",
    step3Title: "3. Мгновенное скачивание", step3Desc: "Мы конвертируем ваш файл, и вы скачиваете его за секунды.",
    reviewsKicker: "Отзывы", reviewsTitle: "Тысячи конвертированных файлов",
    review1: "Я конвертировал PDF в Word за секунды, и всё форматирование сохранилось. Идеально.", review2: "Наконец-то смог перевести фото HEIC с iPhone в JPG. Очень быстро.", review3: "Ничего не устанавливая: загружаю файл и скачиваю. Очень просто.",
    faqKicker: "Частые вопросы",
    faq1Q: "Безопасно ли загружать мои файлы?", faq1A: "Да. Файлы обрабатываются безопасно и не передаются третьим лицам.",
    faq2Q: "Какие форматы я могу конвертировать?", faq2A: "PDF ↔ Word, Excel, PowerPoint, JPG и PNG, а также HEIC→JPG, WEBP→JPG и HTML→PDF.",
    faq3Q: "Нужно ли что-то устанавливать?", faq3A: "Нет. Всё работает в браузере, на любом устройстве.",
    faq4Q: "Сколько это стоит?", faq4A: "0,50 € за конвертацию.",
    toastConverting: "Конвертируем…", toastDone: "Готово! Загрузка началась.", toastError: "Не удалось конвертировать файл.",
  },
  uk: {
    eyebrow: "Конвертер файлів", h1: "Конвертуйте будь-який файл", sub: "Завантажте файл, і ми підкажемо, у що його можна конвертувати. Або оберіть нижче.",
    drag: "Перетягніть файл сюди", selectBtn: "Вибрати файл", anyFormat: "Будь-який формат · до 100 МБ",
    uploaded: "Файл завантажено", change: "Змінити",
    whichFormat: "У який формат конвертувати?", unsupported: "Ми поки не можемо конвертувати цей тип файлу.",
    convertTo: "Конвертувати у {f}",
    converting: "Конвертуємо ваш файл…", ready: "Ваш файл готовий!", download: "Завантажити", preparing: "Підготовка…", convertAnother: "Конвертувати в інший формат",
    allConversions: "Усі конвертації",
    trustPrivate: "Приватно та безпечно", trustDevice: "Будь-який пристрій", trustNoInstall: "Без встановлення",
    howKicker: "Як це працює", howTitle: "Конвертуйте за 3 кроки",
    step1Title: "1. Завантажте файл", step1Desc: "Перетягніть або виберіть будь-який файл. Ми визначимо тип автоматично.",
    step2Title: "2. Оберіть формат", step2Desc: "Ми покажемо, у що можна конвертувати. Натисніть потрібний.",
    step3Title: "3. Миттєве завантаження", step3Desc: "Ми конвертуємо ваш файл, і ви завантажуєте його за секунди.",
    reviewsKicker: "Що кажуть", reviewsTitle: "Тисячі конвертованих файлів",
    review1: "Я конвертував PDF у Word за секунди, і все форматування збереглося. Ідеально.", review2: "Нарешті зміг перевести фото HEIC з iPhone у JPG. Дуже швидко.", review3: "Нічого не встановлюючи: завантажую файл і скачую. Дуже просто.",
    faqKicker: "Часті запитання",
    faq1Q: "Чи безпечно завантажувати мої файли?", faq1A: "Так. Файли обробляються безпечно й не передаються третім особам.",
    faq2Q: "Які формати я можу конвертувати?", faq2A: "PDF ↔ Word, Excel, PowerPoint, JPG і PNG, а також HEIC→JPG, WEBP→JPG і HTML→PDF.",
    faq3Q: "Чи потрібно щось встановлювати?", faq3A: "Ні. Усе працює в браузері, на будь-якому пристрої.",
    faq4Q: "Скільки це коштує?", faq4A: "0,50 € за конвертацію.",
    toastConverting: "Конвертуємо…", toastDone: "Готово! Завантаження почалося.", toastError: "Не вдалося конвертувати файл.",
  },
  ro: {
    eyebrow: "Convertor de fișiere", h1: "Convertește orice fișier", sub: "Încarcă fișierul și îți spunem în ce îl poți converti. Sau alege mai jos.",
    drag: "Trage fișierul aici", selectBtn: "Selectează fișier", anyFormat: "Orice format · până la 100 MB",
    uploaded: "Fișier încărcat", change: "Schimbă",
    whichFormat: "În ce format îl convertim?", unsupported: "Încă nu putem converti acest tip de fișier.",
    convertTo: "Convertește în {f}",
    converting: "Se convertește fișierul…", ready: "Fișierul tău este gata!", download: "Descarcă", preparing: "Se pregătește…", convertAnother: "Convertește în alt format",
    allConversions: "Toate conversiile",
    trustPrivate: "Privat și sigur", trustDevice: "Orice dispozitiv", trustNoInstall: "Fără instalare",
    howKicker: "Cum funcționează", howTitle: "Convertește în 3 pași",
    step1Title: "1. Încarcă fișierul", step1Desc: "Trage sau selectează orice fișier. Detectăm automat tipul.",
    step2Title: "2. Alege formatul", step2Desc: "Îți arătăm în ce îl poți converti. Apasă pe cel dorit.",
    step3Title: "3. Descarcă instant", step3Desc: "Convertim fișierul și îl descarci în câteva secunde.",
    reviewsKicker: "Ce spun oamenii", reviewsTitle: "Mii de fișiere convertite",
    review1: "Am convertit un PDF în Word în câteva secunde și a păstrat tot formatul. Perfect.", review2: "În sfârșit am putut transforma pozele HEIC de pe iPhone în JPG. Foarte rapid.", review3: "Fără să instalez nimic: încarc fișierul și îl descarc. Foarte ușor.",
    faqKicker: "Întrebări frecvente",
    faq1Q: "Este sigur să îmi încarc fișierele?", faq1A: "Da. Fișierele sunt procesate în siguranță și nu sunt partajate cu terți.",
    faq2Q: "Ce formate pot converti?", faq2A: "PDF ↔ Word, Excel, PowerPoint, JPG și PNG, plus HEIC→JPG, WEBP→JPG și HTML→PDF.",
    faq3Q: "Trebuie să instalez ceva?", faq3A: "Nu. Totul funcționează în browser, pe orice dispozitiv.",
    faq4Q: "Cât costă?", faq4A: "0,50 € pe conversie.",
    toastConverting: "Se convertește…", toastDone: "Gata! Descărcarea a început.", toastError: "Nu s-a putut converti fișierul.",
  },
  zh: {
    eyebrow: "文件转换器", h1: "转换任何文件", sub: "上传您的文件，我们会告诉您可以转换成什么。或在下方选择。",
    drag: "将文件拖到这里", selectBtn: "选择文件", anyFormat: "任何格式 · 最大 100 MB",
    uploaded: "文件已上传", change: "更换",
    whichFormat: "转换成什么格式？", unsupported: "我们暂时无法转换此类文件。",
    convertTo: "转换为 {f}",
    converting: "正在转换您的文件…", ready: "您的文件已就绪！", download: "下载", preparing: "正在准备…", convertAnother: "转换为其他格式",
    allConversions: "所有转换",
    trustPrivate: "私密且安全", trustDevice: "任何设备", trustNoInstall: "无需安装",
    howKicker: "如何使用", howTitle: "3 步完成转换",
    step1Title: "1. 上传文件", step1Desc: "拖动或选择任何文件，我们会自动识别类型。",
    step2Title: "2. 选择格式", step2Desc: "我们会显示可转换的格式，点击您想要的即可。",
    step3Title: "3. 即时下载", step3Desc: "我们转换您的文件，几秒钟即可下载。",
    reviewsKicker: "用户评价", reviewsTitle: "已转换数千个文件",
    review1: "我几秒钟就把 PDF 转成了 Word，格式全部保留。完美。", review2: "我终于能把 iPhone 的 HEIC 照片转成 JPG 了。非常快。", review3: "无需安装任何东西：上传文件即可下载。非常简单。",
    faqKicker: "常见问题",
    faq1Q: "上传我的文件安全吗？", faq1A: "安全。文件会被安全处理，不会与第三方共享。",
    faq2Q: "我可以转换哪些格式？", faq2A: "PDF ↔ Word、Excel、PowerPoint、JPG 和 PNG，以及 HEIC→JPG、WEBP→JPG 和 HTML→PDF。",
    faq3Q: "我需要安装什么吗？", faq3A: "不需要。一切都在浏览器中运行，适用于任何设备。",
    faq4Q: "费用是多少？", faq4A: "每次转换 0.50 €。",
    toastConverting: "正在转换…", toastDone: "完成！下载已开始。", toastError: "无法转换文件。",
  },
};

export function hubT(lang: string): HubStrings {
  return HUB_STRINGS[lang] || HUB_STRINGS.en;
}
