/* =============================================================
   EditorPDF Email Service — Resend integration
   Sends transactional emails for payment confirmation, etc.
   ============================================================= */

import { Resend } from "resend";
import { brandName } from "./brand";

const resend = process.env.RESEND_API_KEY
  ? new Resend(process.env.RESEND_API_KEY)
  : null;

// All transactional mail goes from support@editorpdf.net so users can
// just reply and the message lands in the support inbox (Cloudflare
// Email Routing forwards support@ → the gmail behind it). One unified
// From keeps deliverability + reputation under a single address.
const FROM_ADDRESS = `${brandName} <support@editorpdf.net>`;
const FROM_ADDRESS_VERIFIED = FROM_ADDRESS;
const REPLY_TO_ADDRESS = "support@editorpdf.net";

/**
 * Send a password reset link. The token is generated by the caller
 * (`forgotPassword` in routers.ts) and stored on the user row; we just
 * deliver it. Uses the verified noreply@editorpdf.net domain so the link
 * arrives in the inbox, not spam.
 */
export async function sendPasswordResetEmail({
  to,
  name,
  resetUrl,
}: {
  to: string;
  name?: string | null;
  resetUrl: string;
}): Promise<boolean> {
  if (!resend) {
    console.warn("[Email] Resend not configured, skipping password reset email");
    return false;
  }

  const greeting = name ? `Hola ${name}` : "Hola";
  const html = `
<!DOCTYPE html>
<html lang="es">
<head><meta charset="UTF-8" /><title>Restablecer contraseña — ${brandName}</title></head>
<body style="margin:0;padding:0;background:#f0f4f8;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f0f4f8;padding:40px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">
        <tr><td style="background:#0A0A0B;padding:32px 40px;text-align:center;">
          <span style="color:#fff;font-size:26px;font-weight:700;letter-spacing:-0.5px;">
            Editor<span style="color:#E63946;">PDF</span>
          </span>
        </td></tr>
        <tr><td style="padding:40px 40px 24px;">
          <h1 style="margin:0 0 8px;font-size:22px;color:#0A0A0B;font-weight:700;">Restablecer tu contraseña</h1>
          <p style="margin:0 0 24px;color:#475569;font-size:15px;line-height:1.6;">
            ${greeting}, hemos recibido una solicitud para cambiar la contraseña de tu cuenta de ${brandName}. Pulsa el botón para crear una nueva.
          </p>
          <table cellpadding="0" cellspacing="0" style="margin:0 0 24px;"><tr><td>
            <a href="${resetUrl}" style="display:inline-block;background:#E63946;color:#fff;text-decoration:none;padding:14px 32px;border-radius:10px;font-size:15px;font-weight:600;">
              Crear nueva contraseña
            </a>
          </td></tr></table>
          <p style="margin:0 0 8px;color:#64748b;font-size:13px;line-height:1.6;">
            Si el botón no funciona, copia y pega este enlace en tu navegador:
          </p>
          <p style="margin:0 0 24px;word-break:break-all;font-size:12px;color:#475569;background:#f8fafc;padding:10px 12px;border-radius:6px;border:1px solid #e2e8f0;">
            ${resetUrl}
          </p>
          <p style="margin:0;color:#94a3b8;font-size:12px;line-height:1.6;">
            El enlace caduca en 1 hora. Si no fuiste tú quien hizo la solicitud, puedes ignorar este correo — tu contraseña actual sigue funcionando.
          </p>
        </td></tr>
        <tr><td style="background:#f8faff;padding:20px 40px;border-top:1px solid #e2e8f0;">
          <p style="margin:0;color:#94a3b8;font-size:12px;">
            © 2026 ${brandName} · <a href="https://editorpdf.net" style="color:#94a3b8;">editorpdf.net</a> · ¿Preguntas? <a href="mailto:${REPLY_TO_ADDRESS}" style="color:#94a3b8;">${REPLY_TO_ADDRESS}</a>
          </p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>
  `.trim();

  try {
    const result = await resend.emails.send({
      from: FROM_ADDRESS_VERIFIED,
      to,
      replyTo: REPLY_TO_ADDRESS,
      subject: `Restablecer tu contraseña en ${brandName}`,
      html,
    });
    if (result.error) {
      console.error("[Email] Failed to send password reset email:", result.error);
      return false;
    }
    console.log("[Email] Password reset email sent to:", to, "id:", result.data?.id);
    return true;
  } catch (err) {
    console.error("[Email] Error sending password reset email:", err);
    return false;
  }
}

/**
 * Reply to a contact-form message from the admin panel. `userMessage` is the
 * original message (rendered as a quoted block) so the user has context;
 * `replyBody` is what the admin typed.
 */
export async function sendContactReplyEmail({
  to,
  toName,
  originalSubject,
  originalMessage,
  replyBody,
}: {
  to: string;
  toName: string;
  originalSubject: string;
  originalMessage: string;
  replyBody: string;
}): Promise<boolean> {
  if (!resend) {
    console.warn("[Email] Resend not configured, skipping contact reply email");
    return false;
  }

  // Escape minimal HTML so user-submitted text doesn't break the layout
  const esc = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const replyHtml = esc(replyBody).replace(/\n/g, "<br />");
  const originalHtml = esc(originalMessage).replace(/\n/g, "<br />");

  const html = `
<!DOCTYPE html>
<html lang="es">
<head><meta charset="UTF-8" /><title>Re: ${esc(originalSubject)}</title></head>
<body style="margin:0;padding:0;background:#f0f4f8;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f0f4f8;padding:40px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">
        <tr><td style="background:#0A0A0B;padding:24px 40px;text-align:center;">
          <span style="color:#fff;font-size:22px;font-weight:700;letter-spacing:-0.5px;">
            Editor<span style="color:#E63946;">PDF</span>
          </span>
        </td></tr>
        <tr><td style="padding:32px 40px 16px;">
          <p style="margin:0 0 16px;color:#475569;font-size:15px;line-height:1.6;">
            Hola ${esc(toName)}, gracias por contactar con ${brandName}. Esta es nuestra respuesta a tu mensaje:
          </p>
          <div style="margin:0 0 28px;padding:16px 20px;background:#f8fafc;border-left:3px solid #E63946;border-radius:6px;color:#0f172a;font-size:14px;line-height:1.7;">
            ${replyHtml}
          </div>
          <p style="margin:0 0 8px;color:#64748b;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;">Tu mensaje original</p>
          <div style="margin:0 0 28px;padding:14px 18px;background:#fafafa;border:1px solid #e2e8f0;border-radius:6px;color:#64748b;font-size:13px;line-height:1.6;">
            <strong>Asunto:</strong> ${esc(originalSubject)}<br /><br />
            ${originalHtml}
          </div>
          <p style="margin:0;color:#94a3b8;font-size:12px;line-height:1.6;">
            Para continuar la conversación, simplemente responde a este email.
          </p>
        </td></tr>
        <tr><td style="background:#f8faff;padding:20px 40px;border-top:1px solid #e2e8f0;">
          <p style="margin:0;color:#94a3b8;font-size:12px;">© 2026 ${brandName} · <a href="https://editorpdf.net" style="color:#94a3b8;">editorpdf.net</a></p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>
  `.trim();

  try {
    const result = await resend.emails.send({
      from: FROM_ADDRESS_VERIFIED,
      to,
      replyTo: REPLY_TO_ADDRESS,
      subject: `Re: ${originalSubject}`,
      html,
    });
    if (result.error) {
      console.error("[Email] Failed to send contact reply:", result.error);
      return false;
    }
    console.log("[Email] Contact reply sent to:", to, "id:", result.data?.id);
    return true;
  } catch (err) {
    console.error("[Email] Error sending contact reply:", err);
    return false;
  }
}

/**
 * Send a payment confirmation email after a successful subscription
 */
export async function sendPaymentConfirmationEmail({
  to,
  name,
  trialEndDate,
  monthlyPrice,
  trialPrice = "0€",
  cancelUrl,
}: {
  to: string;
  name: string;
  trialEndDate: Date;
  monthlyPrice?: string;
  trialPrice?: string;
  cancelUrl: string;
}): Promise<boolean> {
  // Default monthlyPrice to the live admin-set price (site_settings.subscription_price_eur)
  // when the caller doesn't override it. Falls back to 19,99€ if the setting is empty.
  if (!monthlyPrice) {
    const { getActiveMonthlyPrice } = await import("./db");
    monthlyPrice = (await getActiveMonthlyPrice()).formatted;
  }

  const formattedDate = trialEndDate.toLocaleDateString("es-ES", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const html = `
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Confirmación de pago — ${brandName}</title>
</head>
<body style="margin:0;padding:0;background:#f0f4f8;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f0f4f8;padding:40px 0;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">
          <!-- Header -->
          <tr>
            <td style="background:#1a3c6e;padding:32px 40px;text-align:center;">
              <span style="color:#ffffff;font-size:26px;font-weight:700;letter-spacing:-0.5px;">
                Editor<span style="color:#60a5fa;">PDF</span>
              </span>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:40px 40px 24px;">
              <h1 style="margin:0 0 8px;font-size:22px;color:#1a3c6e;font-weight:700;">
                ✅ ¡Pago confirmado!
              </h1>
              <p style="margin:0 0 24px;color:#475569;font-size:15px;line-height:1.6;">
                Hola <strong>${name}</strong>, tu período de prueba de 7 días ha comenzado. Ya tienes acceso completo a todas las funciones de ${brandName}.
              </p>

              <!-- Summary box -->
              <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8faff;border:1px solid #e2e8f0;border-radius:8px;margin-bottom:24px;">
                <tr>
                  <td style="padding:20px 24px;">
                    <p style="margin:0 0 12px;font-size:13px;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:0.5px;">Resumen de tu suscripción</p>
                    <table width="100%" cellpadding="0" cellspacing="0">
                      <tr>
                        <td style="padding:6px 0;color:#475569;font-size:14px;">Cargo inicial (prueba 7 días)</td>
                        <td align="right" style="padding:6px 0;color:#1a3c6e;font-size:14px;font-weight:600;">${trialPrice}</td>
                      </tr>
                      <tr>
                        <td style="padding:6px 0;color:#475569;font-size:14px;">Precio mensual tras el período de prueba</td>
                        <td align="right" style="padding:6px 0;color:#1a3c6e;font-size:14px;font-weight:600;">${monthlyPrice}/mes</td>
                      </tr>
                      <tr>
                        <td colspan="2" style="padding-top:12px;border-top:1px solid #e2e8f0;"></td>
                      </tr>
                      <tr>
                        <td style="padding:6px 0;color:#475569;font-size:14px;">Fin del período de prueba</td>
                        <td align="right" style="padding:6px 0;color:#1a3c6e;font-size:14px;font-weight:600;">${formattedDate}</td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>

              <!-- Important notice -->
              <table width="100%" cellpadding="0" cellspacing="0" style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;margin-bottom:24px;">
                <tr>
                  <td style="padding:16px 20px;">
                    <p style="margin:0;color:#92400e;font-size:13px;line-height:1.6;">
                      <strong>⚠️ Recuerda:</strong> Si no cancelas antes del <strong>${formattedDate}</strong>, se te cobrarán automáticamente <strong>${monthlyPrice}/mes</strong> hasta que canceles. Puedes cancelar en cualquier momento desde tu cuenta.
                    </p>
                  </td>
                </tr>
              </table>

              <p style="margin:0 0 24px;color:#475569;font-size:15px;line-height:1.6;">
                Puedes cancelar tu suscripción en cualquier momento antes de que finalice el período de prueba sin ningún coste adicional.
              </p>

              <!-- CTA buttons -->
              <table cellpadding="0" cellspacing="0" style="margin-bottom:32px;">
                <tr>
                  <td style="padding-right:12px;">
                    <a href="https://editorpdf.net/es/dashboard" style="display:inline-block;background:#1a3c6e;color:#ffffff;text-decoration:none;padding:12px 24px;border-radius:8px;font-size:14px;font-weight:600;">
                      Ir a mi panel
                    </a>
                  </td>
                  <td>
                    <a href="${cancelUrl}" style="display:inline-block;background:#ffffff;color:#1a3c6e;text-decoration:none;padding:12px 24px;border-radius:8px;font-size:14px;font-weight:600;border:1.5px solid #1a3c6e;">
                      Cancelar suscripción
                    </a>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="background:#f8faff;padding:24px 40px;border-top:1px solid #e2e8f0;">
              <p style="margin:0 0 8px;color:#94a3b8;font-size:12px;line-height:1.6;">
                Has recibido este email porque completaste una compra en <a href="https://editorpdf.net" style="color:#1a3c6e;">editorpdf.net</a>. Si no reconoces esta compra, contacta con nosotros en <a href="mailto:support@editorpdf.net" style="color:#1a3c6e;">support@editorpdf.net</a>.
              </p>
              <p style="margin:0;color:#94a3b8;font-size:12px;">
                © 2026 ${brandName} — <a href="https://editorpdf.net/es/terms" style="color:#94a3b8;">Términos de uso</a> · <a href="https://editorpdf.net/es/privacy" style="color:#94a3b8;">Privacidad</a> · <a href="${cancelUrl}" style="color:#94a3b8;">Cancelar suscripción</a>
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();

  if (!resend) {
    console.warn("[Email] Resend not configured, skipping confirmation email");
    return false;
  }

  try {
    const result = await resend.emails.send({
      from: FROM_ADDRESS,
      to,
      subject: `✅ Confirmación de pago — ${brandName} (prueba 7 días)`,
      html,
    });

    if (result.error) {
      console.error("[Email] Failed to send confirmation email:", result.error);
      return false;
    }

    console.log("[Email] Confirmation email sent to:", to, "id:", result.data?.id);
    return true;
  } catch (err) {
    console.error("[Email] Error sending confirmation email:", err);
    return false;
  }
}

/**
 * Send a cancellation confirmation email when user cancels their subscription
 */
export async function sendCancellationEmail({
  to,
  name,
  accessUntilDate,
  reactivateUrl,
}: {
  to: string;
  name: string;
  accessUntilDate: Date;
  reactivateUrl: string;
}): Promise<boolean> {
  const formattedDate = accessUntilDate.toLocaleDateString("es-ES", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const html = `
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Suscripción cancelada — ${brandName}</title>
</head>
<body style="margin:0;padding:0;background:#f0f4f8;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f0f4f8;padding:40px 0;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">
          <!-- Header -->
          <tr>
            <td style="background:#1a3c6e;padding:32px 40px;text-align:center;">
              <span style="color:#ffffff;font-size:26px;font-weight:700;letter-spacing:-0.5px;">
                Editor<span style="color:#60a5fa;">PDF</span>
              </span>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:40px 40px 24px;">
              <h1 style="margin:0 0 8px;font-size:22px;color:#1a3c6e;font-weight:700;">
                Suscripción cancelada
              </h1>
              <p style="margin:0 0 24px;color:#475569;font-size:15px;line-height:1.6;">
                Hola <strong>${name}</strong>, hemos recibido tu solicitud de cancelación. Tu suscripción ha sido cancelada correctamente.
              </p>

              <!-- Access info box -->
              <table width="100%" cellpadding="0" cellspacing="0" style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;margin-bottom:24px;">
                <tr>
                  <td style="padding:20px 24px;">
                    <p style="margin:0 0 8px;font-size:13px;font-weight:600;color:#1976D2;text-transform:uppercase;letter-spacing:0.5px;">✅ Tu acceso continúa</p>
                    <p style="margin:0;color:#15803d;font-size:15px;line-height:1.6;">
                      Aunque has cancelado, seguirás teniendo acceso completo a todas las funciones de ${brandName} hasta el <strong>${formattedDate}</strong>. No se realizará ningún cargo adicional.
                    </p>
                  </td>
                </tr>
              </table>

              <p style="margin:0 0 24px;color:#475569;font-size:15px;line-height:1.6;">
                Si cambias de opinión, puedes reactivar tu suscripción en cualquier momento antes del <strong>${formattedDate}</strong> sin perder el acceso ni pagar de nuevo.
              </p>

              <!-- CTA buttons -->
              <table cellpadding="0" cellspacing="0" style="margin-bottom:32px;">
                <tr>
                  <td style="padding-right:12px;">
                    <a href="${reactivateUrl}" style="display:inline-block;background:#1a3c6e;color:#ffffff;text-decoration:none;padding:12px 24px;border-radius:8px;font-size:14px;font-weight:600;">
                      Reactivar suscripción
                    </a>
                  </td>
                  <td>
                    <a href="https://editorpdf.net/es/dashboard" style="display:inline-block;background:#ffffff;color:#1a3c6e;text-decoration:none;padding:12px 24px;border-radius:8px;font-size:14px;font-weight:600;border:1.5px solid #1a3c6e;">
                      Ir a mi panel
                    </a>
                  </td>
                </tr>
              </table>

              <p style="margin:0 0 8px;color:#94a3b8;font-size:13px;line-height:1.6;">
                ¿Tuviste algún problema o quieres contarnos por qué cancelaste? Escríbenos a <a href="mailto:support@editorpdf.net" style="color:#1a3c6e;">support@editorpdf.net</a> — tu opinión nos ayuda a mejorar.
              </p>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="background:#f8faff;padding:24px 40px;border-top:1px solid #e2e8f0;">
              <p style="margin:0;color:#94a3b8;font-size:12px;line-height:1.6;">
                © 2026 ${brandName} — <a href="https://editorpdf.net/es/terms" style="color:#94a3b8;">Términos de uso</a> · <a href="https://editorpdf.net/es/privacy" style="color:#94a3b8;">Privacidad</a>
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();

  if (!resend) {
    console.warn("[Email] Resend not configured, skipping cancellation email");
    return false;
  }

  try {
    const result = await resend.emails.send({
      from: FROM_ADDRESS,
      to,
      subject: `Tu suscripción a ${brandName} ha sido cancelada`,
      html,
    });

    if (result.error) {
      console.error("[Email] Failed to send cancellation email:", result.error);
      return false;
    }

    console.log("[Email] Cancellation email sent to:", to, "id:", result.data?.id);
    return true;
  } catch (err) {
    console.error("[Email] Error sending cancellation email:", err);
    return false;
  }
}
